### DISCUSSION TITLE
Issue reporting page for brew not working.

### DISCUSSION THREAD

**Discussion by abcbarryn** [Homebrew/discussions#2526] [Everyday usage]
The page at https://github.com/Homebrew/brew/issues/new?assignees=&labels=bug&template=bug.yml fails to submit an issue and returns error 400 when you click submit.

**Comment by carlocab** [comment]
See #2505, #2465. Please file a ticket with GitHub, since that's not something we can fix.

**Reply by abcbarryn** [reply]
I see someone else has already done that. I might do so as well if I knew where/how to.

**Reply by luckman212** [reply]
Apparently the site to report this to GH is: https://support.github.com/contact/bug-report

**Reply by luckman212** [reply]
I filed GH ticket #1409253

**Comment by luckman212** [comment]
**I received this response back from Github on my ticket. Seems like the fix can be made on our side (hopefully @carlocab can try it!)**

---

Hi Luke,

I have heard back from the team, and it turns out there was a recent change made to requirements for issue forms. The `label` field is now required for checkbox attributes. This was changed to prevent the same options from being triggered across different checkboxes.

If you or a maintainer replace the current checkboxes section:

```
- type: checkboxes
    attributes:
      description: Please verify that you've followed these steps.
      options:
        - label: I ran `brew update` and am still able to reproduce my issue.
          required: true
        - label: I have resolved all warnings from `brew doctor` and that did not fix my problem.
          required: true
```

with one that includes a label, the issue form should successfully submit again. For example, I added a label of "Verification", but as long as it has a label it can be something else:

```
- type: checkboxes
    attributes:
      label: Verification
      description: Please verify that you've followed these steps.
      options:
        - label: I ran `brew update` and am still able to reproduce my issue.
          required: true
        - label: I have resolved all warnings from `brew doctor` and that did not fix my problem.
          required: true
```

The team is now working on getting the documentation updated, as well as improving the validity checking in the form creation editor to check for this.

Sorry for the frustration, but please let us know if there is anything else we can do for you and we will be happy to assist!

Thanks,

Tammy  
GitHub Support
