### DISCUSSION TITLE
QtWebEngineQuick of Qt6 on Linux

### DISCUSSION THREAD

**Discussion by amirmasoudabdol** [Homebrew/discussions#2978] [Linux] [answered]
I’m trying to setup a GitHub Action for building my project, and I need to install Qt. I have tried the brew formula and it works fine but I see that `QtWebEngineQuick` is not installed and my CMake config fails with this:

```log
-- Could NOT find Qt6WebEngineQuick (missing: Qt6WebEngineQuick_DIR)
CMake Error at Desktop/CMakeLists.txt:27 (find_package):
  Found package configuration file:
    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT FOUND. 
  Failed to find Qt component "WebEngineQuick".

  Expected Config file at does NOT exist
```

I'm setting up the dependencies, and installing Qt like this:

```yaml
      - name: Dependencies
        run: |
          sudo apt-get -y install build-essential mercurial gfortran-9 gfortran-10 flex bison r-base cmake libarchive-dev zlibc libzstd-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev
          brew install qt
```

Am I missing something, or is this not just possible because of unavailability of WebEngineQuick dependencies, e.g., node.js and python2, on Ubuntu 20.04?
