### DISCUSSION TITLE
Deduplicate and Cleanup GitHub Actions

### DISCUSSION THREAD

**Discussion by mohzulfikar** [Homebrew/discussions#3376] [Tap maintenance and Homebrew development]
Hi there, I'm planning to change some CI in homebrew project. The First one that I want to be grouped with composite action is this code on `homebrew-core`.
```yaml
      - name: Failures summary for brew test-bot --only-formulae
        if: always()
        run: |
          touch bottles/steps_output.txt
          cat bottles/steps_output.txt
          rm bottles/steps_output.txt
      - name: Output brew bottle result
        if: always()
        run: |
          cat bottles/bottle_output.txt
          rm bottles/bottle_output.txt
```

The link to the action workflow is here:
1. [dispatch-rebottle](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/dispatch-rebottle.yml)
2. [dispatch-build-bottle](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/dispatch-build-bottle.yml)

Any additional suggestions or comments? Thank you
