### DISCUSSION TITLE
brew meson fails since Nov 5

### DISCUSSION THREAD

**Discussion by davea42** [Homebrew/discussions#3942] [Everyday usage] [answered]
The workflow here worked fine two weeks ago, Nov 5 2022
Now is a failing github workflow:
Other workflows, identical except not installing meson,
still work fine.

Suggestions?
Thanks in advance.
```
name: ci_mac_meson

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos_meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: tools
      run:  |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install meson ninja
    - name:
      run:  |
        mkdir builddir && cd builddir
        meson . .. -Ddwarfexample=true
        ninja
        ninja test
```
[brew.txt](https://github.com/Homebrew/discussions/files/10050202/brew.txt)
