### DISCUSSION TITLE
Testing homebrew for Windows in GitHUB Actions

### DISCUSSION THREAD

**Discussion by jkitchin** [Homebrew/discussions#4464] [Everyday usage] [answered]
### Output of `brew config`

```shell
N/A
```

### Output of `brew doctor`

```shell
N/A
```

### Description of issue

Has anyone tried setting up a GitHUB action with `os: windows-latest` for testing homebrew and formulas? I have been trying to use https://github.com/Vampire/setup-wsl to get a WSL system, but I am stuck trying to install brew since it appears to work as root, and I can't figure out how to change the user.

**Comment by ZhongRuoyu** [comment, marked as answer]
You may want to set [`wsl-shell-user`](https://github.com/Vampire/setup-wsl#wsl-shell-user) like this:

```yaml
      - name: Install WSL
        uses: Vampire/setup-wsl@v2
        with:
          wsl-shell-user: linuxbrew
```

From `Vampire/setup-wsl`'s [readme](https://github.com/Vampire/setup-wsl#wsl-shell-user):

> ### wsl-shell-user
> The distribution user that should be used to execute `run`-step scripts with wsl-shell wrapper scripts that are created or updated by the current action invocation. If no value is given, the default user of the distribution at script execution time is used. If the user does not yet exists in the distribution, it is automatically added.

**Comment by jkitchin** [comment]
Thanks! This was the key indeed. Here is the yml that ended up working for me, in case anyone comes along with a similar issue. The current file can be found at https://github.com/jkitchin/homebrew-scimax/tree/main/.github/workflows. 

```
name: scimax-windows

on:
  push:
    branches:
      - main
#    paths:
#      - "Formula/scimax.rb"      

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        with:
          wsl-shell-user: linuxbrew

      - shell: wsl-bash -u root {0}
        run: |
          whoami
          apt update && apt-get install --yes build-essential curl file git

      - shell: wsl-bash -u linuxbrew {0}
        run : |          
          whoami
          which curl
          which git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          brew doctor     # your brew command here
```
