### DISCUSSION TITLE
The new bottle creation workflow for taps is amazing!

### DISCUSSION THREAD

**Discussion by ladislas** [Homebrew/discussions#549] [Tap maintenance and Homebrew development]
Hi there! --

A few days ago, I finally had the time to move from Azure Pipelines to the new GA workflow for bottle creation for our tap https://github.com/osx-cross/homebrew-avr

The reference workflow was of great help but I struggled a little bit with the token part when the repo is own by an organization. We have a test bot account so I used this account for the PAT. I had to reference the PAT as a secret for the repository as `${{ github.token }}` was not working.

But then, the homebrew/git-setup-step was still referencing me (the PR creator) when I wanted our test bot to be.

In the end, the following fixed the issues -- I don't know if it can be improved, but it works and is simple enough so I won't touch it.

```yaml
# start with checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.OSX_CROSS_AVR_HOMEBREW_GITHUB_API_TOKEN }}"

# [...]

# then just setup git -- much quicker than the action
      - name: Set up git
        run: |
          git config --global user.name "osxCrossTestBot"
          git config --global user.email "osxCrossTestBot@leka.io"
```

The whole configuration is available here: https://github.com/osx-cross/homebrew-avr/tree/master/.github/workflows

A big thank you for the homebrew team for putting that together and make it so easy for us tap maintainers to provide bottles for our users :)
