### DISCUSSION TITLE
brew bump-formula-pr output error despite bump PR being opened

### DISCUSSION THREAD

**Discussion by rgoldberg** [Homebrew/discussions#5832] [Everyday usage] [answered]
### Output of `brew config`

```shell
?
```

### Output of `brew doctor`

```shell
?
```

### Description of issue

The `brew bump-formula-pr` command in the GitHub workflow at the end of this issue output an error during [this run](https://github.com/mas-cli/mas/actions/runs/12512809500/job/34906595209), despite the [bump PR](https://github.com/Homebrew/homebrew-core/pull/202536) having been successfully created in `homebrew-core`.

Reference value from the error message: `AE64:3EEB96:9271CC9:95BFC6F:676E4ADC`.

[Link to the full log](https://productionresultssa19.blob.core.windows.net/actions-results/76557750-aab4-4913-89c9-64c785b966d4/workflow-job-run-61dc7ddf-a6df-52bf-9a9b-3b355d641ce4/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-12-27T07%3A10%3A23Z&sig=tJh%2BdF6EhChfHZeuQdA0J8yDrTyNUfENtTew6gW1YnU%3D&ske=2024-12-27T15%3A01%3A45Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-12-27T03%3A01%3A45Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-12-27T07%3A00%3A18Z&sv=2024-11-04).

Log of the step where `brew bump-formula-pr` output an error.

```text
Run brew bump-formula-pr\
  brew bump-formula-pr\
   --tag "${GITHUB_REF_NAME}"\
   --revision "${GITHUB_SHA}"\
   --fork-org "${GITHUB_REPOSITORY_OWNER}"\
   --no-browse\
   --online\
   --strict\
   --verbose\
   mas
  shell: /usr/bin/arch -arm64 /bin/zsh -Negku {0}
  env:
    HOMEBREW_GITHUB_API_TOKEN: ***
Warning: bump-formula-pr is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off


Error: Failed to parse JSON response
unexpected token at '{
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `AE64:3EEB96:9271CC9:95BFC6F:676E4ADC` when reporting this issue."
      }
   ]
}
{"data":{"viewer":{"login":"github-actions[bot]","pullRequests":{"totalCount":0,"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}}}}}
'
Error: Process completed with exit code 1.
```

Workflow:

```yml
#
# .github/workflows/release-published.yml
#
---
name: release-published
on:
  release:
    types: [published]
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/zsh -Negku {0}
jobs:
  release-published:
    if: ${{!github.event.repository.fork}}
    runs-on: macos-15
    steps:
      - name: 🛒 Checkout repo
        env:
          GIT_CONFIG_COUNT: 1
          GIT_CONFIG_KEY_0: init.defaultBranch
          GIT_CONFIG_VALUE_0: ${{github.event.repository.default_branch}}
        uses: actions/checkout@v4

      - name: 🚰 Apply pr-pull label to custom tap formula bump PR
        env:
          TOKEN_APP_ID: ${{secrets.TOKEN_APP_ID}}
          TOKEN_APP_INSTALLATION_ID: ${{secrets.TOKEN_APP_INSTALLATION_ID}}
          TOKEN_APP_PRIVATE_KEY: ${{secrets.TOKEN_APP_PRIVATE_KEY}}
        run: |
          export GH_TOKEN="$(script/generate_token)"
          unsetopt errexit
          bump_url="$(gh release -R "${GITHUB_REPOSITORY}" download "${GITHUB_REF_NAME}" -p bump.url -O - 2>/dev/null)"
          found_bump_url="${?}"
          setopt errexit
          if [[ "${found_bump_url}" -eq 0 ]]; then
            [[ -n "${bump_url}" ]] && gh pr edit "${bump_url}" --add-label pr-pull
            gh release -R "${GITHUB_REPOSITORY}" delete-asset "${GITHUB_REF_NAME}" bump.url -y
          else
            printf $'No custom tap formula bump PR URL found for tag\'%s\'\n' "${GITHUB_REF_NAME}"
          fi
      - name: 🍺 Bump homebrew-core formula
        if: ${{!github.event.release.prerelease}}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{github.token}}
        run: |
          brew bump-formula-pr\
           --tag "${GITHUB_REF_NAME}"\
           --revision "${GITHUB_SHA}"\
           --fork-org "${GITHUB_REPOSITORY_OWNER}"\
           --no-browse\
           --online\
           --strict\
           --verbose\
           mas
```
